### ISSUE TITLE
Theme request: MDC theme

### ISSUE THREAD

**Issue by maicol07** [sweetalert2/sweetalert2-themes#41]
Hi,
is it possible to get a SweetAlert2 theme using MDC?
Reference: https://material.io/develop/web/
Thanks

**Comment by gverni** [comment]
Hi @maicol07 do you mean a material-ui theme? That is already available.

**Comment by maicol07** [comment]
MDC has a different style than Material UI

**Comment by gverni** [comment]
Would you care for elaborating on exactly what’s your request @maicol07? Material-ui and MDC are two implementations of the material design guidelines, so they are visually very similar. Since i’m not a designer, can you explain what would you change in the Sweetalert2 material-ui theme appearance to make it MDC?

**Comment by maicol07** [comment]
@gverni ripples on buttons (more rounded), inputs like MD specs ones

**Comment by gverni** [comment]
I agree on the ripple @maicol07 because this is actually defined in the MD guidelines. I can try to add it to the material-ui theme if it's not overcomplicating the SCSS. For what concern the input, as you know MD guidelines provide different types of inputs, and we decided to go for the `Text Field without label` one. We are limited in only using CSS for theming, so we may not be able to implement all of the effects for all of the items.

**Comment by gverni** [comment]
Closed in favor of #42
