### ISSUE TITLE
dark.min.css (and dark.css?) compiled incorrectly.

### ISSUE THREAD

**Issue by xrqss** [sweetalert2/sweetalert2-themes#58]
There seems to be an issue with colouring. I have fixed this by adding an !important keyword to `color: #e1e1e1` inside of the .swal2-title definition. I am not sure if this is the same for dark.css

https://gyazo.com/188ba89851d198aced4780d8a9fce1be

**Comment by limonte** [comment]
Thanks for reporting, but I don't get what's the issue. In order to improve the quality of reported issues I just added the templates. Please report the issue following the "Bug report" template:

![image](https://user-images.githubusercontent.com/6059356/87965128-efdea200-cac3-11ea-8249-d6e1d8e5907e.png)
